# Generated by Django 5.2.11 on 2026-08-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_delete_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False, help_text="Privé : seul le créateur voit ce chantier — et, par héritage, tout ce qu'il contient. La visibilité des enfants se CALCULE à la lecture (core.visibility) ; rien n'est écrit sur eux, sinon dé-privatiser ne saurait plus ce qui était privé avant."),
        ),
    ]
