# Generated by Django 5.2.11 on 2026-08-22 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_groups_become_categories'),
        ('projects', '0008_delete_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_projects', to='budget.budget'),
        ),
    ]
